import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SiteHeader } from "@/components/site-header";
import {ChildrenOnly} from "@/types/components_argument"
import { cn } from "@/lib/utils";
import { useTheme } from "next-themes";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function SiteBody({children}:ChildrenOnly) {
  return <body className={cn("max-w-screen-2xl mx-auto border-2", inter.className)}>{children}</body>
}

export default function RootLayout({
  children,
}: ChildrenOnly) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head/>
      <SiteBody>
        <Providers>
          <SiteHeader/>
          {children}
        </Providers>
      </SiteBody>
    </html>
  );
}
